# Dataset description :
student_id – Unique identifier for each student

age – Age of the student

gender – Student gender

cgpa – Academic performance score (4.5 to 10 scale)

branch – Field of study (CSE, IT, ECE, Mechanical, etc.)

college_tier – College tier classification

attendance_percentage – Attendance rate

backlogs – Number of academic backlogs

study_hours_per_day – Daily study hours

Technical Skills and Experience

coding_skill_score – Programming skill level

aptitude_score – Aptitude test score

logical_reasoning_score – Logical reasoning ability

certifications_count – Number of certifications completed

projects_count – Number of projects completed

github_repos – Number of GitHub repositories

internships_count – Number of internships completed

Professional and Communication Skills

communication_skill_score – Communication ability

mock_interview_score – Mock interview performance

linkedin_connections – Number of LinkedIn connections

Personal and Extracurricular Factors

extracurricular_score – Extracurricular participation score

leadership_score – Leadership ability score

volunteer_experience – Volunteer experience (Yes/No)

sleep_hours – Average sleep duration

placement_status – Indicates whether the student got offered a job

salary_package_lpa – Salary offered in Lakhs Per Annum

In [2]:
import warnings
warnings.filterwarnings("ignore")

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

from IPython.display import display, Markdown

from sklearn.model_selection import train_test_split
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler, MinMaxScaler, PowerTransformer, PolynomialFeatures
from sklearn.linear_model import LinearRegression, Ridge
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import  mean_absolute_error, mean_squared_error, r2_score

## 1. Loading the dataset

In [3]:
import os

data_path = "student.csv"
df = pd.read_csv(data_path)
print("Using dataset:", data_path)
print("Shape:", df.shape)

display(df.head())

Using dataset: student.csv
Shape: (100000, 26)

,student_id,age,gender,cgpa,branch,college_tier,internships_count,projects_count,certifications_count,coding_skill_score,...,mock_interview_score,attendance_percentage,backlogs,extracurricular_score,leadership_score,volunteer_experience,sleep_hours,study_hours_per_day,placement_status,salary_package_lpa
0,1,24,Male,7.53,IT,Tier 2,4,6,1,99.238568,...,72.647009,77.463863,2,63.382726,52.938240,Yes,6.7,3.6,Not Placed,0.00
1,2,21,Male,7.92,CSE,Tier 2,1,3,6,80.966123,...,61.699110,88.887600,1,73.694605,60.198856,No,4.4,2.3,Not Placed,0.00
2,3,22,Female,8.60,EEE,Tier 1,0,1,1,49.177184,...,87.396911,74.153265,0,63.329294,43.708803,No,8.8,5.9,Placed,11.99
3,4,24,Male,6.68,CSE,Tier 1,0,2,2,79.359084,...,58.401069,87.635955,1,47.636099,56.549154,Yes,8.1,4.4,Not Placed,0.00
4,5,20,Female,8.43,IT,Tier 3,1,4,3,65.018573,...,74.489201,79.120749,1,0.000000,67.268893,No,8.7,3.4,Placed,12.16

## 2. Dataset Overview

We check for:
- data types
- missing values
- duplicates

In [7]:
display(df.info())

<class 'pandas.DataFrame'>
RangeIndex: 100000 entries, 0 to 99999
Data columns (total 26 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   student_id                 100000 non-null  int64
 1   age                        100000 non-null  int64
 2   gender                     100000 non-null  str
 3   cgpa                       100000 non-null  float64
 4   branch                     100000 non-null  str
 5   college_tier               100000 non-null  str
 6   internships_count          100000 non-null  int64
 7   projects_count             100000 non-null  int64
 8   certifications_count       100000 non-null  int64
 9   coding_skill_score         100000 non-null  float64
 10  aptitude_score             100000 non-null  float64
 11  communication_skill_score  100000 non-null  float64
 12  logical_reasoning_score    100000 non-null  float64
 13  hackathons_participated    100000 non-null  int64
 14  github_repos               100000 non-null  int64
 15  linkedin_connections       100000 non-null  int64
 16  mock_interview_score       100000 non-null  float64
 17  attendance_percentage      100000 non-null  float64
 18  backlogs                   100000 non-null  int64
 19  extracurricular_score      100000 non-null  float64
 20  leadership_score           100000 non-null  float64
 21  volunteer_experience       100000 non-null  str
 22  sleep_hours                100000 non-null  float64
 23  study_hours_per_day        100000 non-null  float64
 24  placement_status           100000 non-null  str
 25  salary_package_lpa         100000 non-null  float64
dtypes: float64(12), int64(9), str(5)
memory usage: 19.8 MB

None

We can oviously see that no values are missing so it isn't needed to

In [8]:
display(df.describe(include='all').T)

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
student_id,100000.0,NaN,NaN,NaN,50000.5,28867.657797,1.0,25000.75,50000.5,75000.25,100000.0
age,100000.0,NaN,NaN,NaN,21.00574,1.999562,18.0,19.0,21.0,23.0,24.0
gender,100000,2,Male,60028,NaN,NaN,NaN,NaN,NaN,NaN,NaN
cgpa,100000.0,NaN,NaN,NaN,7.49689,0.992834,4.5,6.82,7.5,8.18,10.0
branch,100000,6,CSE,34818,NaN,NaN,NaN,NaN,NaN,NaN,NaN
college_tier,100000,3,Tier 2,49955,NaN,NaN,NaN,NaN,NaN,NaN,NaN
internships_count,100000.0,NaN,NaN,NaN,1.50223,1.22528,0.0,1.0,1.0,2.0,8.0
projects_count,100000.0,NaN,NaN,NaN,3.00186,1.731764,0.0,2.0,3.0,4.0,13.0
certifications_count,100000.0,NaN,NaN,NaN,2.00515,1.416553,0.0,1.0,2.0,3.0,11.0
coding_skill_score,100000.0,NaN,NaN,NaN,69.825326,14.694618,20.0,59.807945,70.00625,80.058762,100.0
aptitude_score,100000.0,NaN,NaN,NaN,64.988108,14.844093,20.0,54.8946,65.011394,75.079266,100.0
communication_skill_score,100000.0,NaN,NaN,NaN,67.960744,13.846636,20.0,58.587535,67.973221,77.503749,100.0
logical_reasoning_score,100000.0,NaN,NaN,NaN,65.931696,14.82679,20.0,55.940547,66.003829,76.113705,100.0
hackathons_participated,100000.0,NaN,NaN,NaN,1.00069,0.997908,0.0,0.0,1.0,2.0,8.0
github_repos,100000.0,NaN,NaN,NaN,4.00516,2.004897,0.0,3.0,4.0,5.0,16.0
linkedin_connections,100000.0,NaN,NaN,NaN,524.55911,274.993479,50.0,287.0,523.0,764.0,999.0
mock_interview_score,100000.0,NaN,NaN,NaN,69.989411,11.937257,20.0,61.973172,70.026665,78.122083,100.0
attendance_percentage,100000.0,NaN,NaN,NaN,84.730169,9.416075,50.0,78.325833,85.018828,91.782511,100.0
backlogs,100000.0,NaN,NaN,NaN,0.49759,0.708434,0.0,0.0,0.0,1.0,6.0
extracurricular_score,100000.0,NaN,NaN,NaN,59.894049,19.549666,0.0,46.53859,60.079021,73.549567,100.0
leadership_score,100000.0,NaN,NaN,NaN,54.937526,19.781197,0.0,41.43239,55.07621,68.530115,100.0
volunteer_experience,100000,2,No,59963,NaN,NaN,NaN,NaN,NaN,NaN,NaN
sleep_hours,100000.0,NaN,NaN,NaN,6.983319,1.468113,3.0,6.0,7.0,8.0,10.0
study_hours_per_day,100000.0,NaN,NaN,NaN,3.523124,1.471248,0.5,2.5,3.5,4.5,10.0
placement_status,100000,2,Placed,54459,NaN,NaN,NaN,NaN,NaN,NaN,NaN
salary_package_lpa,100000.0,NaN,NaN,NaN,7.252106,6.735132,0.0,0.0,11.1,13.47,20.44